//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class deneyimlerim
    {
        public int id { get; set; }
        public string Baslik { get; set; }
        public string altBaslik { get; set; }
        public string aciklama { get; set; }
        public string tarih { get; set; }
    }
}
