//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<deneyimlerim> deneyimlerim { get; set; }
        public virtual DbSet<egitimlerim> egitimlerim { get; set; }
        public virtual DbSet<hakkimda> hakkimda { get; set; }
        public virtual DbSet<hobilerim> hobilerim { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<sertifikalarim> sertifikalarim { get; set; }
        public virtual DbSet<yeteneklerim> yeteneklerim { get; set; }
        public virtual DbSet<sosyalmedya> sosyalmedya { get; set; }
    }
}
